#!/bin/bash
# symlink dotfiles and scripts

[[ ! "$DOTFILES" ]] && \
    DOTFILES="$(dirname "$(readlink -f "$0")")"

_make_symlink(){
    mkdir -p $(dirname "$2")
    if [ -h "$2" ] || [ ! -e "$2" ]; then
        case "$3" in
            sudo)
                echo -e "\033[31msudo link:\033[0m $(basename "$2")"
                sudo rm "$2"
                ;;
            *)
                echo -e "\033[31mlink:\033[0m $(basename "$2")"
                rm "$2"
                ;;
        esac
    fi
    if [ ! -h "$2" ]; then
        case "$3" in
            sudo)
                echo -en "\033[32msudo link:\033[0m "
                sudo ln -fvs "$1" "$2"
                ;;
            *)
                echo -en "\033[32mlink:\033[0m "
                ln -fvs "$1" "$2"
                ;;
        esac
    fi
}

cat $(pwd)/configs/gps | while read line; do
  _make_symlink $line
done
