#!/bin/bash
lspciR=$(lspci -v | grep -A1 -e VGA -e 3D)

install_type=$1

getPackages(){
	local category=$1
	local list=$2
	local inter=$(grep $category <<< $list)
	echo ${inter#${category}:}
}



xorgList=$(cat xorg.stuff)
laptopPackages=$(getPackages laptop "$xorgList" )
thinkpadPackages=$(getPackages thinkpad "$xorgList" )
xorgPackages=$(getPackages base "$xorgList" )

checkGPUs(){
	if grep $1 <<< "$lspciR" > /dev/null
	then
		return 0
	else
		return 1
	fi
}

gpuPackages(){
	checkGPUs AMD
	case "$?" in 
	  0) local amdP=$(getPackages amd "$xorgList" ) ;;
	  *) local amdP="" ;;
	esac	
	checkGPUs Intel
	case "$?" in 
	  0) local intelP=$(getPackages intel "$xorgList" ) ;;
	  *) local intelP="" ;;
	esac
	checkGPUs NVIDIA
	case "$?" in 
	  0) local nvidiaP=$(getPackages nvidia "$xorgList" ) ;;
	  *) local nvidiaP="" ;;
	esac
	echo "$amdP $intelP $nvidiaP"
}

gpuP=$(gpuPackages)
case "$install_type" in
	"base") result="$gpuP $xorgPackages" ;;
	"laptop")  result="$gpuP $xorgPackages $laptopPackages" ;;
	"thinkpad") result="$gpuP $xorgPackages $laptopPackages $thinkpadPackages" ;;
esac
echo $result