#!/bin/sh

timedatectl
bash ./diskPartition
pacstrap -K /mnt $(cat pacstrap.list)

genfstab -U /mnt >> /mnt/etc/fstab

cp ./chroot /mnt/chroot -r

arch-chroot /mnt bash /chroot/setup

rm -rf /mnt/chroot

