#! /bin/sh

picom &
feh --bg-scale ~/PandorasBox/wp.png

$HOME/.config/polybar/launch.sh

bspc monitor DisplayPort-1 -d 󰣇
bspc monitor HDMI-A-0 -d 󰣇
bspc monitor HDMI-A-1 -d 󰣇 󰙯 

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

bspc config border_width         2
bspc config focused_border_color "#2a9dfb"
bspc config window_gap          10
bspc config top_padding          25

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config top_monocle_padding 10

bspc rule -a copyq state=floating center=true
{google-chrome-stable,
        discord,
        spotify-launcher,
        nautilus}
bspc rule -a discord desktop='󰙯' follow=true
bspc rule -a Spotify desktop='' follow=true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

# change this
(bspc subscribe node_remove | while IFS=' ' read -r e m d n r; do echo '󰣇\n󰙯\n' | grep $(bspc query -D -d --names | perl -pe 'chomp') || (bspc desktop "$d"'.focused.!occupied' -r); done) &

bspc subscribe desktop_add | while IFS=' ' read -r e m d n r; do bspc query -D -d $d --names | grep "^ *$" && bspc desktop "$d" -r; done &

xsetroot -cursor_name left_ptr
