#!/bin/bash
ibus-daemon -drxR
xrdb ~/.Xresources
bash ~/.screens.sh
xhost +local:root > /dev/null
sxhkd &
dunst &
blueman-applet &
nm-applet &
copyq &
exec bspwm &>> "$HOME/bspwm.log"
#exec i3 -V -d all &>> "$HOME/i3.log"
