# If you come from bash you might have to change your $PATH.

export ZSH_DISABLE_COMPFIX=true

# Path to your oh-my-zsh installation.
export ZSH="/home/grk/.oh-my-zsh"
ZSH_THEME="agnoster"

plugins=(git asdf)

source $ZSH/oh-my-zsh.sh

# Settings for Japanese input
export GTK_IM_MODULE='ibus'
export QT_IM_MODULE='ibus'
export XMODIFIERS=@im='ibus'


ned(){
    local pathToFile=$1
    case $1 in
        zrc)
            pathToFile=$HOME/.zshrc
            ;;
        zp)
            pathToFile=$HOME/.zprofile
            ;;

        xrc)
            pathToFile=$HOME/.xinitrc
            ;;
        i3c)
            pathToFile=$HOME/.config/i3/config
            ;;
        polyc)
            pathToFile=$HOME/.config/polybar/config
            ;;
        *)
            ;;
        esac
    sudo nano $pathToFile
}

battery(){
	upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep percentage
	upower -i /org/freedesktop/UPower/devices/battery_BAT1 | grep percentage
}

alias kysfag="poweroff"
alias ll="ls -laF"
macchina