#!/bin/sh

localeConfig(){
	enLocale="en_US.UTF-8"
	ptLocale="pt_PT.UTF-8"
	echo ${enLocale} UTF-8 >> /etc/locale.gen
	echo ${ptLocale} UTF-8 >> /etc/locale.gen
	locale-gen
	echo Lang=${enLocale} >> /etc/locale.conf
}

hostsConfig(){
	read -p "Pick the Hostname:" hostname
	echo $hostname >> /etc/hostname
	echo 127.0.0.1        localhost >> /etc/hosts
	echo ::1              localhost >> /etc/hosts
}

ln -sf /usr/share/zoneinfo/Europe/Lisbon /etc/localtime
hwclock --systohc
localeConfig
hostsConfig
