#!/bin/sh
read -p "Numero de Aluno: a" nAluno
read -s -p "Password: " pass
ifname=$(ip link | grep -Po '\d: (w\w*):' | grep -Po 'w\w*')
nmcli connection add  type wifi ifname $ifname con-name eduroam ssid eduroam -- ipv4.method auto \
 wifi-sec.key-mgmt wpa-eap 802-1x.eap peap \
 802-1x.phase2-auth mschapv2 \
 802-1x.identity  "A${nAluno}@alunos.uminho.pt" 802-1x.password "$pass"


#nmcli con add type wifi ifname $ifname con-name eduroam ssid eduroam
#nmcli con mod eduroam ipv4.method "auto"
#nmcli con mod eduroam 802-1x.eap "peap"
#nmcli con mod eduroam 802-1x.phase2-auth "mschapv2"
#nmcli con mod eduroam 802-1x.identity "A${nAluno}@alunos.uminho.pt"
#nmcli con mod eduroam 802-1x.password "$pass"
#nmcli con mod eduroam wifi-sec.key-mgmt "wpa-eap"
#save
#activate
