#!/bin/sh
if ! ls /sys/firmware/efi/efivars > /dev/null ; then echo "Not in UEFI mode"; exit; fi
timedatectl set-ntp true
bash ./diskPartition
packages=$(cat pacstrap.list)
pacstrap /mnt $packages
genfstab -U /mnt >> /mnt/etc/fstab
read -p "Pick username:" uname
arch-chroot /mnt useradd -m -s /bin/zsh $uname 
arch-chroot /mnt ./configurationStuff
